version: '3.9'

services:
  spring:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_app
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - redis
    environment:
      - DB_PASSWORD
      - ALIYUN_OSS_ACCESS_KEY
      - ALIYUN_OSS_SECRET_KEY
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_nginx
    restart: always
    ports:
      - "8081:80"              # 外部访问前端的端口（原先 nginx 映射 8081）
    depends_on:
      - spring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:6.2
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
